# Generated by Django 6.0.5 on 2026-07-01 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробіг')),
                ('fuel_type', models.CharField(choices=[('BENZIN', 'Бензин'), ('DIESEL', 'Дизель'), ('ELECTRO', 'Електро'), ('HYBRID', 'Гібрид'), ('GAS', 'Газ')], max_length=20, verbose_name='Паливо')),
                ('transmission', models.CharField(choices=[('MANUAL', 'Механіка'), ('AUTOMATIC', 'Автомат'), ('ROBOT', 'Робот'), ('CVT', 'Варіатор')], max_length=20, verbose_name='Коробка')),
                ('body_type', models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('SUV', 'Позашляховик'), ('COUPE', 'Купе'), ('CONVERTIBLE', 'Кабріолет'), ('WAGON', 'Універсал'), ('MINIVAN', 'Мінівен'), ('PICKUP', 'Пікап')], max_length=20, verbose_name='Кузов')),
                ('drive_type', models.CharField(choices=[('FRONT', 'Передній'), ('REAR', 'Задній'), ('FULL', 'Повний')], max_length=20, verbose_name='Привід')),
                ('engine_volume', models.FloatField(blank=True, null=True, verbose_name="Об'єм двигуна")),
                ('engine_power', models.IntegerField(blank=True, null=True, verbose_name='Потужність (к.с.)')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Колір')),
                ('is_new', models.BooleanField(default=False, verbose_name='Нове')),
                ('has_credit', models.BooleanField(default=False, verbose_name='В кредиті')),
                ('has_accident', models.BooleanField(default=False, verbose_name='В ДТП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Головне фото')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Додаткові фото')),
                ('views', models.IntegerField(default=0, verbose_name='Перегляди')),
                ('favorites', models.IntegerField(default=0, verbose_name='В обраних')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Пройшло модерацію')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_views',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
